# Generated by Django 5.2.16 on 2026-07-08 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(default='demo-session', max_length=120)),
                ('messages', models.JSONField(default=list)),
                ('submitted_text', models.TextField(blank=True)),
                ('submitted_schema', models.JSONField(blank=True, null=True)),
                ('submitted_documents', models.JSONField(default=list)),
                ('defense_overrides', models.JSONField(default=dict)),
                ('retrieved_docs', models.JSONField(default=list)),
                ('tool_calls', models.JSONField(default=list)),
                ('model_output', models.TextField(blank=True)),
                ('safe_output', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('pending_confirmation', 'Pending confirmation'), ('error', 'Error')], default='completed', max_length=32)),
                ('timeline', models.JSONField(default=list)),
                ('repair_advice', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('summary', models.TextField()),
                ('chapter_refs', models.JSONField(default=list)),
                ('learning_goals', models.JSONField(default=list)),
                ('allowed_inputs', models.JSONField(default=list)),
                ('system_prompt', models.TextField(blank=True)),
                ('training_targets', models.JSONField(default=list)),
                ('success_conditions', models.JSONField(default=list)),
                ('hints', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=16)),
                ('source', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=240)),
                ('span', models.CharField(blank=True, max_length=180)),
                ('action', models.CharField(choices=[('allowed', 'Allowed'), ('flagged', 'Flagged'), ('normalized', 'Normalized'), ('sanitized', 'Sanitized'), ('blocked', 'Blocked'), ('confirmation_required', 'Confirmation required')], max_length=32)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='scenarios.attempt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_moderation', models.BooleanField(default=True)),
                ('prompt_injection_detection', models.BooleanField(default=True)),
                ('encoding_normalization', models.BooleanField(default=True)),
                ('instruction_data_separation', models.BooleanField(default=True)),
                ('output_moderation', models.BooleanField(default=True)),
                ('tool_policy_enforcement', models.BooleanField(default=True)),
                ('human_confirmation_required', models.BooleanField(default=True)),
                ('rate_limit', models.BooleanField(default=False)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_defenses', to='scenarios.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='scenarios.scenario'),
        ),
        migrations.CreateModel(
            name='ScenarioDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_poisoned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
