# Generated by Django 5.2.16 on 2026-07-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='chat_messages',
            field=models.JSONField(default=list),
        ),
    ]
